name: Bug Report (new)
description: Create a bug report
body:
  - type: markdown
    attributes:
      label: Description of the problem
      value: |
        A clear description of what the bug is, including the expected and actual behavior.
  - type: markdown
    attributes:
      label: Compilation or execution log
      value: |
        Any relevant log that may help to understand the bug.
        Please use [distinct block]https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) to format this section.
  - type: markdown
    attributes:
      label: Minimal code/script to reproduce the problem
      value: |
        Insert your script/code that use QBDI here.
  - type: markdown
    attributes:
      label: Code of the target of the instrumentation
      value: |
        Insert your script/code that you try to instrument with QBDI.
        If the instrumented code is a public library/binary, you may provide a link to download it.
  - type: markdown
    attributes:
      label: Specific command to reproduce your issue
      value: |
        Can you list all the command (if possible shell) that should be run to reproduce the bug.
  - type: markdown
    attributes:
      label: Information about the environment
      value: |
        Version of your environment and any tools that is needed to reproduce the bug
        
        If you use multiples devices (like a computer and a smartphone), please provide the information for each of them.

        - OS: (with version) [e.g. Windows 11, Debian 12.4, Android 14, ...] 
        - Architecture: [e.g. X86, X64, AARCH64, ARM32]
        - QBDI version (returned by getVersion) and commit hash (if not a release version)
        - Frida version on the Host and on the target (in case of android device) (for frida/QBDI issue)
        - Python version (for PyQBDI issue)
  - type: markdown
    attributes:
      label: Additional context or informations
      value: |
        Any other context about the problem here.

        Thanks for taking the time to fill out this report!
